### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by maxpowersi** [s0md3v/Corsy#18]
Hi, in /Corsy/core/tests.py line 38, i have that error. 

I tested using: python3 corsy.py -u "https://54.76.200.24" 

root value is empty y think is because it is an IP.

Regards!

**Comment by Yashvendra** [comment]
Any Updated on this @s0md3v . I'm also facing the same issue. As soon as I started the scan, this came out in the output

```
Traceback (most recent call last):
  File "corsy.py", line 76, in <module>
    result = each.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "corsy.py", line 66, in cors
    return active_tests(url, root, scheme, header_dict, delay)
  File "/home/yash/Documents/GIT/Corsy/core/tests.py", line 38, in active_tests
    headers = requester(url, scheme, header_dict, root + '.example.com')
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by s0md3v** [comment]
This issue has been fixed now.
