### ISSUE TITLE
Error with redirections.

### ISSUE THREAD

**Issue by KathanP19** [s0md3v/Corsy#23]
```

    ＣＯＲＳＹ  {v1.0-beta}

 ~ Estimated scan time: 44 secs
Traceback (most recent call last):
  File "corsy.py", line 76, in <module>
    result = each.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "corsy.py", line 66, in cors
    return active_tests(url, root, scheme, header_dict, delay)
  File "/home/natsu/myproject/tools/Corsy/core/tests.py", line 26, in active_tests
    headers = requester(url, scheme, header_dict, 'example.com')
  File "/home/natsu/myproject/tools/Corsy/core/requester.py", line 9, in requester
    response = requests.get(url, headers=headers, verify=False).headers
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 165, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```

**Comment by s0md3v** [comment]
This issue has been fixed now.
