### ISSUE TITLE
Self CA Handling

### ISSUE THREAD

**Issue by Pitenager** [s0md3v/Corsy#3]
Hi dude, 

I wanted to test my webapp using your tool and it crashes due to my SSL certificate is self-signed.

This is the crash:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 332, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sparta-barclays.labs.stratio.com', port=443): Max retries exceeded with url: /?User-Agent=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%3B+rv%3A70.0%29+Gecko%2F20100101+Firefox%2F70.0&Accept=text%2Fhtml%2Capplication%2Fxhtml%2Bxml%2Capplication%2Fxml%3Bq%3D0.9%2C%2A%2F%2A%3Bq%3D0.8&Accept-Language=en-US%2Cen%3Bq%3D0.5&Accept-Encoding=gzip&DNT=1&Connection=close&Origin=httpsexample.com (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "corsy.py", line 43, in <module>
    result = cors(target_url, delay)
  File "corsy.py", line 36, in cors
    active = active_tests(url, root, scheme, delay)
  File "/home/pruiz/Escritorio/tools/Corsy/core/tests.py", line 22, in active_tests
    acao_header = requester(url, scheme, 'example.com')
  File "/home/pruiz/Escritorio/tools/Corsy/core/requester.py", line 14, in requester
    response = requests.get(url, headers).headers
  File "/usr/lib/python3/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='sparta-barclays.labs.stratio.com', port=443): Max retries exceeded with url: /?User-Agent=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%3B+rv%3A70.0%29+Gecko%2F20100101+Firefox%2F70.0&Accept=text%2Fhtml%2Capplication%2Fxhtml%2Bxml%2Capplication%2Fxml%3Bq%3D0.9%2C%2A%2F%2A%3Bq%3D0.8&Accept-Language=en-US%2Cen%3Bq%3D0.5&Accept-Encoding=gzip&DNT=1&Connection=close&Origin=httpsexample.com (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
```

Greetings,

**Comment by s0md3v** [comment]
Dude, the host `http://sparta-barclays.labs.stratio.com` isn't up, how is it supposed to respond?

**Comment by Pitenager** [comment]
Yes, it's up but in a self environment.

**Comment by Pitenager** [comment]
@s0md3v Please, add `verify=False` when you call the request method. This will fix the problem with self CA.

Thank you.
